replicaCount: 3
image:
  repository: ghcr.io/isirajieinnocent/time-printer
  tag: d8ec42d1b44d0de19812a11a65a28a1294a0d698
  pullPolicy: IfNotPresent
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
