replicaCount: 3

image:
  repository: ghcr.io/isirajieinnocent/time-printer
  tag: latest  # This gets updated to the Git SHA by GitHub Actions
  pullPolicy: IfNotPresent

podImage: "your-image"
spotInstanceTolerationKey: "spot-instance"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
