replicaCount: 3

image:
  repository: ghcr.io/isirajieinnocent/time-printer
  tag: f9fddcf84a77c958f02d4e4b8cd62bda926d3d20 # This gets updated to the Git SHA by GitHub Actions
  pullPolicy: IfNotPresent

podImage: "your-image"
spotInstanceTolerationKey: "spot-instance"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

server:
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8080
  extraArgs:
    - --tls-cert-file=/etc/argocd/tls/argocd-server.crt
    - --tls-key-file=/etc/argocd/tls/argocd-server.key
  extraVolumeMounts:
    - name: argocd-server-tls
      mountPath: /etc/argocd/tls
      readOnly: true
  extraVolumes:
    - name: argocd-server-tls
      secret:
        secretName: argocd-server-tls
