# Application Configuration
replicaCount: 3
image:
  repository: ghcr.io/isirajieinnocent/time-printer
  tag: f2ff37a1d5f82f353552d4b6ba24bcc2c77e4733 # This gets updated to the Git SHA by GitHub Actions
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-creds # Add if pulling from private registry
podImage: "your-image"
# Spot Instance Configuration
spotInstanceTolerationKey: "spot-instance"
tolerations:
  - key: "spot-instance"
    operator: "Exists"
    effect: "NoSchedule"
# Security Hardening
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
# Resource Management
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
# Autoscaling Configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
# Server Configuration
server:
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: 8080
        protocol: TCP
      - name: https
        port: 443
        targetPort: 8443
        protocol: TCP
  # TLS Configuration
  extraArgs:
    - --tls-cert-file=/etc/argocd/tls/tls.crt
    - --tls-key-file=/etc/argocd/tls/tls.key
    - --insecure=false
  extraVolumeMounts:
    - name: argocd-server-tls
      mountPath: /etc/argocd/tls/tls.crt
      readOnly: true
      subPath: tls.crt
    - name: argocd-server-tls
      mountPath: /etc/argocd/tls/tls.key
      readOnly: true
      subPath: tls.key
  extraVolumes:
    - name: argocd-server-tls
      secret:
        secretName: argocd-server-tls
        defaultMode: 0400
