replicaCount: 3
image:
  repository: ghcr.io/isirajieinnocent/time-printer
<<<<<<< HEAD
  tag: a9689774b738444641f17cb1557fadbfd7ef9ec9
=======
  tag: dd09091cbb04cf8b726b1156b20ec9a6f5ddfa41 # This gets updated to the Git SHA by GitHub Actions
>>>>>>> 74ec1d20f911ecc5d0f9f9557c7bf7d1b769311a
  pullPolicy: IfNotPresent
podImage: "your-image"
spotInstanceTolerationKey: "spot-instance"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

server:
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8080
  
  extraArgs:
    - --insecure  # Remove this in production
    # - --secure   # Uncomment for production

  # TLS configuration (uncomment for production)
  # config:
  #   tls.crt: |
  #     -----BEGIN CERTIFICATE-----
  #     ...
  #   tls.key: |
  #     -----BEGIN PRIVATE KEY-----
  #     ...