# Application Configuration
replicaCount: 3

image:
  repository: ghcr.io/isirajieinnocent/time-printer
  tag: b1c1acee4a9336bf09927e945768ac4ea1180ee7 # Auto-updated by CI/CD
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-creds  # Add if pulling from private registry

podImage: "your-image"  # Consider using full image reference if different from above

# Spot Instance Configuration
spotInstanceTolerationKey: "spot-instance"
tolerations:
  - key: "spot-instance"
    operator: "Exists"
    effect: "NoSchedule"

# Security Hardening
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

# Resource Management
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Autoscaling Configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80  # Added memory metric

# Service Configuration
service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  annotations: {}
  labels: {}

# TLS Configuration (Production Ready)
tls:
  enabled: true
  secretName: argocd-server-tls
  certFile: /etc/argocd/tls/tls.crt
  keyFile: /etc/argocd/tls/tls.key
  caFile: /etc/argocd/tls/ca.crt  # Optional for mutual TLS

# Server Configuration
server:
  extraArgs:
    - --tls-cert-file=/etc/argocd/tls/tls.crt
    - --tls-key-file=/etc/argocd/tls/tls.key
    - --insecure=false  # Force TLS

  extraVolumeMounts:
    - name: argocd-server-tls
      mountPath: /etc/argocd/tls
      readOnly: true
      subPath: tls.crt  # More secure mounting
    - name: argocd-server-tls
      mountPath: /etc/argocd/tls
      readOnly: true
      subPath: tls.key

  extraVolumes:
    - name: argocd-server-tls
      secret:
        secretName: argocd-server-tls
        defaultMode: 0400
        items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key

# Monitoring Configuration (Optional)
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s

# Network Policies
networkPolicy:
  enabled: true
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: 8443
          protocol: TCP