apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: time-printer
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: my-python-app # Namespace where the app will be deployed
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/isirajieinnocent/gitops-argocd-deployment" 
    targetRevision: HEAD  
    path: src/app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  