apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-printer-app
  namespace: time-printer  # Update the namespace here
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-printer-app  # Label selector for the pods
  template:
    metadata:
      labels:
        app: time-printer-app  # Label for the pod
    spec:
      containers:
        - name: time-printer-app
          image: myorg/time-printer-app:latest  # Replace with your image
          ports:
            - containerPort: 5000  # Expose the correct port
          resources:
            requests:
              memory: "512Mi"  # Minimum resources
              cpu: "250m"  # Minimum CPU allocation
            limits:
              memory: "1Gi"  # Max resources
              cpu: "500m"  # Max CPU
          env:
            - name: ENVIRONMENT
              value: "production"  # Example environment variable
