apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: time-printer
spec:
  project: default
  source:
    repoURL: https://github.com/your-repo/ci-cd-pipeline.git
    path: src/helm/my-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true